name: CI

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install gfortran google-perftools
        # export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
        python -m pip install --upgrade pip
        pip install --no-cache-dir -U -r requirements.txt | cat
    - name: Test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pytest -v --cov=lab --cov-report term-missing
        coveralls
